Repository Decathlon/pull-request-labeler-action, pull requests merged in 2019-06, with the labels that each got.

#2 feat: added maintainer information into Dockerfile
  Dockerfile
Labels: enhancement

#1 fix: project name in package.json was incorrect
  package.json
Labels: bug

#8 feat: using absolute picture link for hub.docker.com documentation
  README.md
  assets/intro.png
  assets/screenshot.png
Labels: documentation

#7 feat: Add milestone closure action
  .github/main.workflow
Labels: enhancement

#10 fix: wrong variable values
  .github/main.workflow
Labels: bug

#14 feat(labels): avoid removing all labels
  README.md
  src/entrypoint.ts
  src/utils.ts
  tests/utils.test.ts
Labels: enhancement

#13 feat: refactor circleci build
  .circleci/config.yml
Labels: enhancement

#15 feat: added circleci build badge on the readme file
  README.md
Labels: documentation, enhancement

#3 feat: added auto dependencies update via DependaBot
  .dependabot/config.yml
Labels: enhancement
